<%
        def pluralForm = api.pluralForm(entity.uncapitalizedClassName)
        tableId = "${pluralForm}DataGrid"
%>
package ${packageName}

import ${entity.fqn}
<%if (!api.jmixProjectModule.isApplication() || routeLayout == null) {%>
import io.jmix.flowui.view.DefaultMainViewParent
<%} else {%>
import ${routeLayout.getControllerFqn()}
<%}%>
import com.vaadin.flow.router.Route
import io.jmix.flowui.view.*
import org.springframework.beans.factory.annotation.Autowired

<%if (classComment) {%>
${classComment}
<%}%>@Route(value = "${listRoute}", layout = <%if (!api.jmixProjectModule.isApplication() || routeLayout == null) {%>DefaultMainViewParent::class<%} else {%>${routeLayout.getControllerClassName()}::class<%}%>)
@ViewController(id = "${viewId}")
@ViewDescriptor(path = "${viewDescriptorName}.xml")
@LookupComponent("${tableId}")
@DialogMode(width = "64em")
class ${viewControllerName} : StandardListView<${entity.className}>() {

    // generated by the project template together with ${viewControllerName}Helper and ${fragmentControllerName}
    @Autowired
    private lateinit var helper: ${viewControllerName}Helper

    @Subscribe
    fun onInit(event: InitEvent) {
        helper.describe()
    }
}
