package ${packageName}

import ${entity.fqn}
import com.vaadin.flow.component.orderedlayout.VerticalLayout
import io.jmix.flowui.fragment.Fragment
import io.jmix.flowui.fragment.FragmentDescriptor
import io.jmix.flowui.model.InstanceContainer
import io.jmix.flowui.view.ViewComponent

<%if (classComment) {%>
${classComment}
<%}%>/**
 * ADDITIONAL FILE generated by the project template studio-templates/flowui/crm-list-view.
 */
@FragmentDescriptor("${fragmentDescriptorName}.xml")
class ${fragmentControllerName} : Fragment<VerticalLayout>() {

    @ViewComponent
    private lateinit var ${entity.uncapitalizedClassName}Dc: InstanceContainer<${entity.className}>

    fun set${entity.className}(${entity.uncapitalizedClassName}: ${entity.className}?) {
        ${entity.uncapitalizedClassName}Dc.item = ${entity.uncapitalizedClassName}
    }
}
