package ${packageName};

import ${entity.fqn};
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import io.jmix.flowui.fragment.Fragment;
import io.jmix.flowui.fragment.FragmentDescriptor;
import io.jmix.flowui.model.InstanceContainer;
import io.jmix.flowui.view.ViewComponent;
import org.jspecify.annotations.Nullable;

<%if (classComment) {%>
${classComment}
<%}%>/**
 * ADDITIONAL FILE generated by the project template studio-templates/flowui/crm-list-view.
 */
@FragmentDescriptor("${fragmentDescriptorName}.xml")
public class ${fragmentControllerName} extends Fragment<VerticalLayout> {

    @ViewComponent
    private InstanceContainer<${entity.className}> ${entity.uncapitalizedClassName}Dc;

    public void set${entity.className}(@Nullable ${entity.className} ${entity.uncapitalizedClassName}) {
        ${entity.uncapitalizedClassName}Dc.setItem(${entity.uncapitalizedClassName});
    }
}
