package ${packageName};

import org.springframework.stereotype.Component;

/**
 * ADDITIONAL FILE generated by the project template studio-templates/flowui/crm-list-view.
 * The file name comes from the 'templateFileName' attribute of the source, not from a property.
 */
@Component("${project_id}${viewControllerName}Helper")
public class ${viewControllerName}Helper {

    public String describe() {
        return "${entity.className} list view helper";
    }
}
